issue4 発話API追加　れいか
java-women/cocorobo-pet pull request #59
Opened 2016-09-24 08:46 UTC by AyaEbata

発話API追加
ＰＣの設定ができなかったのでここからコミットしします。

確認お願いします。

2016-09-24 10:25 UTC, AyaEbata commented
ごめんしゃい！！！
最後確認したと思ったら、エンドポイントのURLで確認してましたw
間違えましたw
ちょっともう一回確認します。

2016-09-24 13:11 UTC, AyaEbata commented
@erk5 さん
あやです。修正しました。（最初のプルリクはれいかさん
確認宜しくお願いします。

2016-09-24 21:47 UTC, erk5 commented on cocoroboController/cocorobo-pet/src/main/java/javajo/controller/CocoroboController.java
> +     * @param requestSpeechDTO API Keyとメッセージ
APIキーはサーバ内部に保持しているものを使うようにしてください

2016-09-24 21:49 UTC, erk5 commented on cocoroboController/cocorobo-pet/src/main/java/javajo/controller/CocoroboController.java
> +    public ResponseEntity<SpeechDTO> speech(@PathVariable String cocorobo, @RequestBody RequestSpeechDTO requestSpeechDTO) {
インターフェースがモック作成時から変わってしまってます。。。
インタフェースは変えないようお願いします。

2016-09-24 21:51 UTC, erk5 requested changes
作成ありがとうございます！
コメントしたので確認お願いします。

2016-09-24 21:52 UTC, erk5 commented
@AyaEbata @reika-furihata 
コメントの対応お願いします。

2016-09-24 23:02 UTC, AyaEbata commented on cocoroboController/cocorobo-pet/src/main/java/javajo/controller/CocoroboController.java
> +    public ResponseEntity<SpeechDTO> speech(@PathVariable String cocorobo, @RequestBody RequestSpeechDTO requestSpeechDTO) {
HPにAPIキーとメッセージを渡すって書いてあったから、そっちに合わせてしまいましたΣ

2016-09-25 02:19 UTC, AyaEbata commented
@erk5 さん
APIキーは内部で持たせ、インターフェースを戻しました。
認証は起動5分以内にやらなくてはなので、音声APIが5分以内に叩かれるかわからなかったので、とりあえず音声APIのとこには作りませんでした。
確認宜しくお願いします。

2016-09-25 02:31 UTC, erk5 commented
対応ありがとうございます。マージします！

認証たたくところは検証してから追加しましょう！

2016-09-25 02:31 UTC, merged